config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :items do
    member do
      post :add_to_cart
      delete :remove_from_cart
      delete :delete_association
      put :update_quantity
    end
  end

  resources :categories do
    resources :items, only: %i[index]
  end

  resources :orders, except: %i[update destroy] do
    resources :items, only: %i[index]
    member do
      post :update_status
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index]
      resources :items, only: %i[index] do
        collection do
          post :create_item
        end
      end
    end
  end

  get '*path', to: 'orders#routes_exception'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :user

  paginates_per 5

  validates :order_status, numericality: true

  default_scope { order(created_at: :desc) }

  enum order_status: {
    Ordered: 0,
    Paid: 1,
    Cancelled: 2,
    Completed: 3
  }
end

app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class OrdersController < ApplicationController
      def index
        orders = Order.includes(:user).pluck('users.name', 'users.email', 'orders.created_at', 'orders.updated_at',
                                             'orders.order_status')
        render json: orders
      end
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  include OrderHelper
  include CalculateTotal
  include AuthorizedPolicy

  before_action :find_order, only: %i[show update_status]

  def index
    @orders = filter_orders.page(params[:page]).per(5)
  end

  def new
    @cart.each do |item|
      session[:hash].merge!(item.id => 1)
    end
    find_total
  end

  def create
    if user_signed_in?
      create_for_signed_in
      %i[hash cart].each { |x| session.delete(x) }
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  def show; end

  def update_status
    authorized_user(@order)
    @order.order_status = (params[:status].to_i if params[:status].present?)
    if @order.save
      flash[:notice] = 'Order Updated successfully'
    else
      flash[:alert] = 'Order can not update successfully'
    end
  end

  private

  def create_for_signed_in
    @order = Order.new
    @order.user_id = current_user.id
    @order.order_status = 0
    save_order
  end

  def save_order
    @order.transaction do
      raise 'Error: Order can\'t save because cart is empty.' if @cart.empty?

      @order.save!
      @cart.each do |item|
        @order.order_items.create!(item_id: item.id, quantity: session[:hash][item.id.to_s])
      end
    end
  rescue StandardError => e
    flash[:alert] = e
  end

  def find_order
    @order = Order.find(params[:id])
  end
end

app/helpers/order_helper.rb
# frozen_string_literal: true

module OrderHelper
  def filter_orders
    case params[:status]
    when 'All'
      all_orders
    else
      other_filtered_orders
    end
  end

  def all_orders
    if current_user.admin
      Order.all
    else
      Order.where('user_id = ?', current_user.id)
    end
  end

  def other_filtered_orders
    if current_user.admin
      Order.where('order_status = ?', params[:status])
    else
      Order.where('user_id = ? AND order_status = ?', current_user.id, params[:status])
    end
  end
end

app/views/orders/decrease_quantity.js.erb
$('#quantity_value<%= params[:id] %>').html(" <%= session[:hash][params[:id]]%>");

$('#sub_total<%= params[:id] %>').html(" <%= @price*session[:hash][params[:id]].to_i%>");

$('#total').html(" <%= @total%>");

app/views/orders/increase_quantity.js.erb
$('#quantity_value<%=params[:id]%>').html(" <%= session[:hash][params[:id]]%>");

$('#sub_total<%= params[:id] %>').html(" <%= @price*session[:hash][params[:id]].to_i%>");

$('#total').html(" <%= @total%>");

app/views/orders/index.html.erb
<h4><b>Orders List</b></h4>
<div class = "row justify-content-center m-3">
  <%= link_to "All", orders_path(status: 'All'), class: "btn btn-primary mr-sm-5" %>
  <%= link_to "Ordered", orders_path(status: 0), class: "btn btn-primary mr-sm-5" %>
  <%= link_to "Paid", orders_path(status: 1), class: "btn btn-primary mr-sm-5" %>
  <%= link_to "Cancelled", orders_path(status: 2), class: "btn btn-primary mr-sm-5" %>
  <%= link_to "Completed", orders_path(status: 3), class: "btn btn-primary mr-sm-5" %>
</div>
<table class= "table">
  <thead class="thead-dark col-sm-3">
    <tr>
      <th>Person Name</th>
      <th>Person Email</th>
      <th>Order Time</th>
      <th>Updated at</th>
      <th>Detail</th>
      <th>Status</th>
      <%if current_user&.admin%>
        <th >Option</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order|%>
      <tr>
        <td><%= order.user.name%></td>
        <td><%= order.user.email%></td>
        <td><%= order.created_at.strftime("%F; %T")%></td>
        <td><%= order.updated_at.strftime("%F; %T")%></td>
        <td><%= link_to 'Show', order_items_path(order_id: order.id), method: :GET, class: "btn btn-info" %> </td>
        <td id= 'status_field<%=order.id%>' ><%= order.order_status%></td>
        <% if current_user.admin %> 
          <td><div class="dropdown">
            <button class = "btn btn-secondary dropdown-toggle" type = "button" id = "dropdownMenuButton" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded = "false">
              Status
            </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= button_to 'Ordered', update_status_order_path(order, status: 0), remote: true, class:"dropdown-item" %>
                <%= button_to 'Paid', update_status_order_path(order, status: 1), remote: true, class:"dropdown-item" %>
                <%= button_to 'Cancelled', update_status_order_path(order, status: 2), remote: true, class:"dropdown-item" %>
                <%= button_to 'Completed', update_status_order_path(order, status: 3), remote: true, class:"dropdown-item" %>
              </div>
          </div></td>
        <% end %> 
      </tr>
    <%end%>
  </tbody>
</table>
<div class = 'paginate_style'>
<%= paginate @orders%>
</div>

app/views/orders/new.html.erb
<h4>Shopping Cart</h4>
<table class = "table">
  <thead class="thead-dark">
    <tr>
      <th>Items Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Sub Total</th>
      <th>Detail</th>
    </tr>
  </thead>

  <tbody>
    <% @cart.each do |item| %>
    <tr id = "record<%= item.id %>">
      <td><%= item.name %></td>
      <td><%= item.price%></td>
      <td><%= link_to '-', update_quantity_item_path(item, button_name: 'decrease'), method: :PUT, class: "btn btn-success",remote: true %>
        <span id = 'quantity_value<%= item.id %>'><%= session[:hash][item.id.to_s]%></span>
        <%= link_to '+', update_quantity_item_path(item, button_name: 'increase'), method: :PUT, class: "btn btn-success",remote: true%></td>
      <td id = 'sub_total<%= item.id %>'><%= item.price*session[:hash][item.id.to_s].to_i%></td>
      <td><%= link_to 'Show ', item_path(:id => item.id), class: "btn btn-info" %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<% if @cart.present? %>
  <h4>
    Your total bill is: <b><span id = "total"><%= @total %></span></b>    
    <%= button_to "Check out", orders_path(@cart), class: "btn btn-primary mt-3" %>
  </h4>
<% end %>

app/views/orders/routes_excaption.html.erb
<h4>The page you are looking for don't exist</h4>

app/views/orders/routes_exception.html.erb
<h4>The page you are looking for don't exist</h4>

app/views/orders/show.html.erb
<h4>
  Order Detail<br><br>
  Name: <%= @order.user.name%><br>
  Email: <%= @order.user.email%>
</h4>

<table class= "table ">
  <thead class="thead-dark">
    <tr>
      <th>Item Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Sub Total</th>
      <th>Detail</th>
    </tr>
  </thead>

  <tbody>
  <%@total = 0%>
    <% @order.order_items.each do |order_item|%>
      <tr>
        <td><%= order_item.item.name%></td>
        <td><%= order_item.item.price%></td>
        <td><%= @quantity = order_item.quantity %>
        <td><%= @subtotal = order_item.item.price*@quantity %>
        <% @total += @subtotal%>
        <td><%= link_to 'Show', item_path(id: order_item.item.id, order_id: @order.id), class: "btn btn-info" %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<h4>
  Your total bill is: <%= @total %>   
</h4>

app/views/orders/update_status.js.erb
document.getElementById("status_field<%=@order.id%>").innerHTML = '<%= @order.order_status %>';

    