config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :items do
    member do
      post :add_to_cart
      delete :remove_from_cart
      delete :delete_association
      put :update_quantity
    end
  end

  resources :categories do
    resources :items, only: %i[index]
  end

  resources :orders, except: %i[update destroy] do
    resources :items, only: %i[index]
    member do
      post :update_status
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index]
      resources :items, only: %i[index] do
        collection do
          post :create_item
        end
      end
    end
  end

  get '*path', to: 'orders#routes_exception'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include ImageUploader::Attachment(:image)
  paginates_per 5

  has_many :category_items, dependent: :destroy
  has_many :categories, through: :category_items

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  validates :name, :description, :price, :status, presence: true
  validates :name, length: { minimum: 2, maximum: 32 }
  validates :description, length: { minimum: 5, maximum: 500 }
  validates :price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100_000 }
  validates :status, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }

  default_scope { order(created_at: :desc) }
end

app/controllers/api/v1/items_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ItemsController < ApplicationController
      skip_before_action :verify_authenticity_token
      def index
        items = Item.select('name', 'price', 'description')
        render json: items
      end

      def create_item
        item = Item.new(item_params)
        item.save
      end

      private

      def item_params
        params.require(:item).permit(:name, :description, :price, :status, :image, category_ids: [])
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  include AuthorizedPolicy
  include ItemHelper
  include CalculateTotal

  before_action :find_item, only: %i[show destroy edit update]
  before_action :find_categories, only: %i[new edit]
  before_action only: %i[destroy update edit] do
    authorized_user(@item)
  end

  def index
    @items = finding_items.page(params[:page]).per(5)
    find_category_name
    redirect_to order_path(id: params[:order_id]) if params[:order_id]
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    authorized_user(@item)
    set_status
    if @item.save
      flash[:notice] = 'Item created successfully'
      redirect_to item_path(@item)
    else
      flash[:alert] = error_message(@item)
      redirect_to items_path
    end
  end

  def show; end

  def edit
    return unless params[:status] == '1' || params[:status] == '0'

    @item.status = params[:status].to_i
    redirect_back(fallback_location: root_path) if @item.save
  end

  def update
    if @item.update(item_params)
      flash[:notice] = 'Item was updated successfully.'
      redirect_to item_path(@item)
    else
      flash[:alert] = error_message(@item)
      render 'edit'
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = 'Item was deleted successfully.'
    else
      flash[:alert] = error_message(@item)
    end
    redirect_to items_path
  end

  def update_quantity
    if params[:button_name] == 'decrease'
      decrease
    else
      increase
    end
    @price = Item.find(params[:id]).price
    find_total
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :status, :image, category_ids: [])
  end

  def set_status
    @item.status = if item_params[:status] == 'Available'
                     1
                   else
                     0
                   end
  end

  def finding_items
    if params[:category_id]
      item_for_category
    elsif params[:order_id]
      item_for_order
    else
      Item.all.page(params[:page]).per(5)
    end
  end

  def find_item
    @item = Item.find(params[:id])
  end

  def find_category
    Category.find(params[:category_id])
  end

  def find_categories
    @categories = Category.all.collect { |x| [x.name, x.id] }
  end

  def item_for_category
    Item.includes(:categories).where('categories.id' => params[:category_id].to_i)
  end

  def item_for_order
    Item.includes(:orders).where('orders.id' => params[:order_id].to_i)
  end

  def find_category_name
    @category = find_category.name if params[:category_id] && !find_category.nil?
  end
end

app/helpers/item_helper.rb
# frozen_string_literal: true

module ItemHelper
  def delete_association
    if (category = Category.find(params[:category_id].to_i)) && (item = category.items.find(params[:id].to_i))
      category.items.delete(item)
    end
    redirect_back(fallback_location: root_path)
  end

  def add_to_cart
    session[:cart] << params[:id].to_i unless session[:cart].include?(params[:id].to_i)
    redirect_back(fallback_location: root_path)
  end

  def remove_from_cart
    session[:cart].delete(params[:id].to_i)
    redirect_back(fallback_location: root_path)
  end

  def decrease
    session[:hash][params[:id]] -= 1 if session[:hash][params[:id]] > 1
  end

  def increase
    session[:hash][params[:id]] += 1 if session[:hash][params[:id]] < 100
  end
end

app/views/items/_form.html.erb
<div class="col-md-6 col-md-offset-3 center_class">
  <%= form_with(model: @item, local: true) do |f| %>

    <div class="mb-3">
      <b><%= f.label :name %></b><br />
      <%= f.text_field :name, required: true, autocomplete: "Enter Name", class: "form-control" %>
    </div>

    <div class="mb-3">
      <b><%= f.label :description %></b><br />
      <%= f.text_area :description, required: true, autocomplete: "Enter Description", class: "form-control" %>
    </div>

    <div class="mb-3">
      <b><%= f.label :price %></b><br />
      <%= f.number_field :price, min: 0, max: 99999, required: true, autocomplete: "Enter price", class: "form-control" %>
    </div>

    <div class="mb-3">
      <b><%= f.label :status %></b><br>
     <%= f.select :status, ['Available', 'Out of Stock']%>
    </div>

    <%= f.fields_for :category_item do |p| %>
      <div class="mb-3">
        <b><%= f.label "Category" %></b><br>
        <%= f.select :category_ids, @categories, {}, required: true, multiple: true, class: "form-control" %>
      </div>
    <% end %>
    <div class = "mb-3">
      <%= f.label :image %>
      <%= f.file_field :image, class: "btn btn-secondary", onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes }, accept: "image/*" %>
    </div>

    <div class="actions">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>

  <% end %>
</div>

<%= link_to 'back', items_path, class: "btn btn-dark mr-sm-3" %>

app/views/items/_shows.html.erb
<% if params[:category_id]%>
  <h4>  <b><%= @category%></b></h4> 
<% end %>

<% if current_user&.admin %>
  <h4><%= link_to 'Create new item', new_item_path, class: 'btn btn-primary' %></h4>
<% end %>

<table class= "table">
  <thead class="thead-dark col-sm-3">
    <tr>
      <th>Image</td>
      <th>Items Name</th>
      <th>Detail</th>
      <th>Shopping cart</th>
        <% if current_user&.admin %> 
          <th>Stock Status</th>
          <th colspan="2">Action</th>
        <% end %>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item|%>
        <tr>
          <td><% if item.image_url %>
                <%= cl_image_tag(item.image_url, width: 200)%>
              <% else %>
                <%= image_tag('default.png', width: 200)%>
              <% end %>
          </td>
          <td><b><%= item.name%></b></td>
          <td><%= link_to 'Show item', item_path(id: item.id), class: "btn btn-info" %></td>
          <% if item.status == 1%>
            <td><%= button_to "Remove from cart", remove_from_cart_item_path(item), method: :delete, class: "btn btn-danger #{"none" unless @cart.include?(item)}", id: "Remove#{item.id}" %>

            <%= button_to "Add to cart", add_to_cart_item_path(item),class:"btn btn-success #{"none" if @cart.include?(item)}", id: "Create#{item.id}" %> </td>
          <% else %>
            <td>Out of Stock</td>
          <% end %> 
          <% if current_user&.admin %>
            <td><div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Availability
              </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Out Of Stock', edit_item_path(item, status: 0), method: :GET, class:"dropdown-item" %>
                  <%= link_to 'Available', edit_item_path(item, status: 1), method: :GET, class:"dropdown-item" %>
                </div>
              </div>
            </td>
            <td><%= link_to 'Edit item', edit_item_path(item),class:"btn btn-secondary" %> &nbsp &nbsp
                <%= link_to 'Delete item', item_path(id: item.id), method: :delete, data: {confirm: "Are you sure?"},class:"btn btn-secondary" %></td>
            <% if params[:category_id]%>
              <td><%= link_to "Remove from Category", delete_association_item_path(item, category_id: params[:category_id]), method: :delete, class:"btn btn-danger" %></td>
            <% end %>
          <% end %>
        </tr>
    <%end%>
  </tbody>
</table>
<div class = 'paginate_style'>
  <%= paginate @items%>
</div>

app/views/items/add_to_cart.js.erb
$("#Create<%= params[:id]%>").hide();
$("#Remove<%= params[:id]%>").show();

app/views/items/edit.html.erb
<h3 class = "center_class">Edit a Item</h3>
<%= render 'form' %>

app/views/items/increase.js.erb
$('#quantity_value<%=params[:id]%>').html(" <%= session[:hash][params[:id]]%>");

$('#sub_total<%= params[:id] %>').html(" <%= @price*session[:hash][params[:id]].to_i%>");

$('#total').html(" <%= @total%>");

app/views/items/index.html.erb
<%= render 'shows'%>

app/views/items/new.html.erb
<% if policy(@item).admin %>
  <h3 class = "center_class">Create a new Item</h3>
  <%= render 'form' %>
<% else %>
  <%flash[:alert] = 'Not Authorized...' %>
<% end %>

app/views/items/remove_from_cart.js.erb
$("#Create<%= params[:id]%>").show();
$("#Remove<%= params[:id]%>").hide();

app/views/items/show.html.erb
<h4>Items Details</h4>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Items</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @item.name%></td>
      <td><%= @item.description%></td>
      <td><%= @item.price%></td>   
    </tr>
  </tbody>
</table>

<div class=" text-center">

  <% if @item.image_url %>
    <%= cl_image_tag(@item.image_url, width: 400)%>
  <% else %>
    <%= image_tag('default.png', width: 400)%>
  <% end %>
  <div class = "m-3">
    <% if @item.status == 1%>
      <%= button_to "Remove from cart", remove_from_cart_item_path(@item), method: :delete, class: "btn btn-danger #{"none" unless @cart.include?(@item)}", remote: true, id: "Remove#{@item.id}" %>

      <%= button_to "Add to cart", add_to_cart_item_path(@item),class:"btn btn-success #{"none" if @cart.include?(@item)}", id: "Create#{@item.id}", remote: true %>
    <% else %>
      Out of Stock
    <% end %> 
  </div>
</div>

app/views/items/update_quantity.js.erb
$('#quantity_value<%=params[:id]%>').html(" <%= session[:hash][params[:id]]%>");

$('#sub_total<%= params[:id] %>').html(" <%= @price*session[:hash][params[:id]].to_i%>");

$('#total').html(" <%= @total%>");