config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'items#index'
  devise_for :users

  resources :items do
    member do
      post :add_to_cart
      delete :remove_from_cart
      delete :delete_association
      put :update_quantity
    end
  end

  resources :categories do
    resources :items, only: %i[index]
  end

  resources :orders, except: %i[update destroy] do
    resources :items, only: %i[index]
    member do
      post :update_status
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index]
      resources :items, only: %i[index] do
        collection do
          post :create_item
        end
      end
    end
  end

  get '*path', to: 'orders#routes_exception'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :category_items, dependent: :destroy
  has_many :items, through: :category_items

  validates :name, presence: true, length: { minimum: 2, maximum: 32 }

  default_scope { order(created_at: :desc) }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  include AuthorizedPolicy

  before_action :find_category, only: %i[update edit destroy]

  before_action only: %i[destroy update edit] do
    authorized_user(@category)
  end

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(catergory_params)
    authorized_user(@category)
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      flash[:alert] = error_message(@category)
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(catergory_params)
      flash[:notice] = 'Category was updated successfully.'
      redirect_to categories_path
    else
      flash[:alert] = error_message(@category)
      render 'edit'
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = 'Category was deleted successfully.'
    else
      flash[:alert] = error_message(@category)
    end
    redirect_to categories_path
  end

  private

  def catergory_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_form.html.erb
<div class="col-md-6 col-md-offset-3 center_class">
  <%= form_with(model: @category, local: true) do |f| %>


    <div class="mb-3">
      <b><%= f.label :name %></b><br />
      <%= f.text_field :name, autocomplete: "Enter Name", required: true, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= link_to 'back', categories_path, class: "btn btn-dark mr-sm-3" %>

app/views/categories/edit.html.erb
<h3 class = "center_class">Edit a Category</h3>

<%= render 'form' %>

app/views/categories/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin %>
    <h4><%= link_to 'Create new category', new_category_path, class: 'btn btn-primary' %></h4>
  <% end %>
<% end %>
<table class = "table">
  <thead class="thead-dark w-25">
    <tr>
      <th>Category</th>
      <th>Detail</th>
      <% if current_user&.admin %>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category|%>
      <tr>
        <td><%= category.name%></td>
        <td><%= link_to 'Show ', category_items_path(category_id: category.id), class: "btn btn-info" %></td>
        <% if current_user&.admin %>
          <td><%= link_to 'Edit', edit_category_path(category),class:"btn btn-secondary" %> &nbsp &nbsp
          <%= link_to 'Delete', category_path(id: category.id), method: :delete, data: {confirm: "Are you sure?"},class:"btn btn-secondary"  %></td>
        <% end %>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/categories/new.html.erb
<% if policy(@category).admin %>

<h3 class = "center_class mb-3">Create a new Category</h3>

<%= render 'form' %>
<% else %>
<%flash[:alert] = 'Not Authorized...' %>
<% end %>